### ISSUE TITLE
Automatic Sync?

### ISSUE THREAD

**Issue by advatar** [netreconlab/CareKitSample-ParseCareKit#27]
Would it be possible to use https://github.com/parse-community/ParseLiveQuery-iOS-OSX to keep in sync?

**Comment by cbaker6** [comment]
The [parse-objc](https://github.com/netreconlab/CareKitSample-ParseCareKit/tree/parse-objc) has been updated to use ParseLiveQuery and keeps multiple iOS devices in sync. Be sure to take note of the parse-hipaa branch to use above. ParseLiveQuery doesn't work with watchOS, so it won't help there...
