### ISSUE TITLE
Sign in with Apple

### ISSUE THREAD

**Issue by advatar** [netreconlab/CareKitSample-ParseCareKit#56]
I hacked together an alternative LoginView for when on device. It is a bit ugly in the way I extract the password but I believe that appleIDCredential.user is unique per app and rather hard to guess. 

struct LoginView: View {

    //Anything is @ is a wrapper that subscribes and refreshes the view when a change occurs. List to the last lecture in Section 2 for an explanation
    @ObservedObject private var login = Login()

    private func topassword(_ str: String) -> String {
        let parts = str.split(separator: ".")
        let ret = String(parts[1]).substring(toIndex: 9)
        return "Q" + ret
    }

    var body: some View {
        if login.isLoggedIn {
            MainView()
        } else {
            VStack() {
                Text("Quantify Health")
                    .font(.largeTitle) //These are modifiers of the text view
                    .foregroundColor(.white)
                    .padding([.top], 40)
                Image("exercise.jpg") //Change this image to something that represents your application
                    .resizable()
                    .frame(width: 150, height: 150, alignment: .center)
                    .clipShape(Circle())
                    .overlay(Circle().stroke(Color(.white), lineWidth: 4))
                    .shadow(radius: 10)
                    .padding()
                    .layoutPriority(-100)
                Spacer()
                SignInWithAppleButton(.signIn) { request in
                    request.requestedScopes = [ASAuthorization.Scope.fullName,ASAuthorization.Scope.email]
                } onCompletion: { result in
                    switch result {
                        case .success(let authResults):
                            print("Authorisation successful \(authResults)")
                            switch authResults.credential {
                                case let appleIDCredential as ASAuthorizationAppleIDCredential:
                                    let userIdentifier = appleIDCredential.user
                                    let fullName = appleIDCredential.fullName
                                    let email = appleIDCredential.email
                                    print("userIdentifier \(userIdentifier) fullName \(String(describing: fullName)) email \(String(describing: email))  ")
                                    if let username = appleIDCredential.email, let fullName = appleIDCredential.fullName, let givenName = fullName.givenName, let familyName = fullName.familyName {
                                        print("username \(username) password \(userIdentifier)")
                                        login.signup(username: username, password: topassword(userIdentifier), firstName: givenName, lastName: familyName)
                                    } else if let identityToken = appleIDCredential.identityToken, let jws = try? JWS(compactSerialization: identityToken) {
                                        print(jws.payload)
                                        if let token = try? JSONDecoder().decode(AppleToken.self, from: jws.payload.data()) {
                                            print("\(token) \(token.email)")
                                            if let email = token.email {
                                                print("Logging in using \(email) \(topassword(userIdentifier))")
                                                login.login(username: email, password: topassword(userIdentifier))
                                            }
                                        } else {
                                            print("Could not decode")
                                            if let str = String(data:  jws.payload.data(), encoding: .utf8) {
                                                print(str)
                                            }
                                            if let jsonString = try? JSONSerialization.jsonObject(with: jws.payload.data(), options: .allowFragments) {
                                                print("\(jsonString)")
                                            } else {
                                                print("Could not serialize json")
                                            }
                                        }
                                    }
                                    break
                                default:
                                    break
                            }
                        case .failure(let error):
                            print("Authorisation failed: \(error.localizedDescription)")
                    }
                }.frame(width: 300, height: 50)
                if let error = login.loginError {
                    Text("Error: \(error.message)")
                        .foregroundColor(.red)
                }
                Spacer()
            }.frame(minWidth: 0,
                    maxWidth: .infinity,
                    minHeight: 0,
                    maxHeight: .infinity,
                    alignment: .center)
            .background( LinearGradient(gradient: Gradient(colors: [Color(#colorLiteral(red: 0.06253327429, green: 0.6597633362, blue: 0.8644603491, alpha: 1)),Color(#colorLiteral(red: 0, green: 0.2858072221, blue: 0.6897063851, alpha: 1))]), startPoint: .top, endPoint: .bottom))
            .edgesIgnoringSafeArea(.all)
        }
    }
}

**Comment by advatar** [comment]
Forgot this

import AuthenticationServices
import JOSESwift
import CryptoKit

struct AppleToken: Codable {
    let aud: String?
    let auth_time: Int64?
    let c_hash: String?
    let email: String?
    let email_verified: String?
    let exp: Int64?
    let iat: Int64?
    let iss: String?
    let nonce_supported: Bool?
    let sub: String?
}

extension String {

    var length: Int {
        return count
    }

    subscript (i: Int) -> String {
        return self[i ..< i + 1]
    }

    func substring(fromIndex: Int) -> String {
        return self[min(fromIndex, length) ..< length]
    }

    func substring(toIndex: Int) -> String {
        return self[0 ..< max(0, toIndex)]
    }

    subscript (r: Range<Int>) -> String {
        let range = Range(uncheckedBounds: (lower: max(0, min(length, r.lowerBound)),
                                            upper: min(length, max(0, r.upperBound))))
        let start = index(startIndex, offsetBy: range.lowerBound)
        let end = index(start, offsetBy: range.upperBound - range.lowerBound)
        return String(self[start ..< end])
    }
}

**Comment by cbaker6** [comment]
I don't think the code you provided is needed for Apple login. Since this repo depends on `ParseCareKit`, which depends on `ParseSwift`, you can use [ParseApple](https://github.com/parse-community/Parse-Swift/blob/main/Sources/ParseSwift/Authentication/3rd%20Party/ParseApple.swift) to login after you get the `ASAuthorization` credentials from the Apple Sign in button. You can see more info about 3rd party login for Parse-Swift here: https://github.com/parse-community/Parse-Swift/issues/55

> It is a bit ugly in the way I extract the password but I believe that appleIDCredential.user is unique per app and rather hard to guess.  

Is this documented by Apple? If not, I personally would stay away from it, particularly when designing a medical or health based application using CareKit.

**Comment by cbaker6** [comment]
If you decide to use `ParseApple`, this repo is definitely open to PRs if you would like to open one and add the code for the sign in with Apple button

**Comment by advatar** [comment]
ok, I am not very familiar with Parse. You approach seems better, will fix.

**Comment by cbaker6** [comment]
When using `ParseApple`, your authentication will be tied to the ParseUser so it will be easier to handle in Parse. The documentation for ParseApple can be found here: http://parseplatform.org/Parse-Swift/api/Structs/ParseApple.html

If you find any bugs with ParseApple, be sure to file issues on that repo and I will fix over there. I don't believe many people have tried ParseApple yet, so it's possible you can run into something.

**Comment by cbaker6** [comment]
If you are using parse-hipaa you will also need configure your credentials on there as it currently isn't setup for apple login https://docs.parseplatform.org/parse-server/guide/#apple-authdata

**Comment by cbaker6** [comment]
Note that `ParseApple` can be used directly through `ParseUser`, so after you acquire the credentials from Apple, all you need to do is:

```
User.apple.login(user: String, identityToken: String, completion: (Result<User, ParseError>) -> Void)
```

**Comment by cbaker6** [comment]
After acquiring the credentials from the apple sign in button, you just need:

```swift
User.apple.login(user: String, identityToken: String, completion: (Result<User, ParseError>) -> Void>)
```


It's basically used in a similar way to anonymous login: https://github.com/netreconlab/CareKitSample-ParseCareKit/blob/413b8c380d8220e915004da206d7d8682672c849/OCKSample/Login/Login.swift#L136

**Comment by cbaker6** [comment]
Update on this... Apple SignIn works easiest when using Parse-Swift. If you decide not to use Parse-Swift, I recommend using some other login SDK that leverages an official Apple login process.

If you are using the main branch of Parse-Swift, you can pass the `identityToken` directly:

```
User.apple.login(user: String, identityToken: Data, completion: (Result<User, ParseError>) -> Void>)
```

If you are using <=1.1.4, you will need to convert the `identityToken` to a string before login:

```
guard let identityTokenString = String(data: identityToken, encoding: .utf8) else {
        return
 }
User.apple.login(user: String, identityToken: identityTokenString, completion: (Result<User, ParseError>) -> Void>)
```
