### ISSUE TITLE
WatchConnectivity dependency

### ISSUE THREAD

**Issue by advatar** [netreconlab/CareKitSample-ParseCareKit#57]
When synching with cloud, can I get rid of the WatchConnectivity dependency in order to be able to run on macOS

**Comment by cbaker6** [comment]
`WatchConnectivity` is used by iOS and watchOS devices to either share a session token (from iOS to watchOS) when `syncWithCloud = true` or sync data between each other when `syncWithCloud = false`. An iOS app can function without `WatchConnectivity` and can be removed if you don't plan having your app work with watchOS.

As for macOS, this repo only supports what CareKit supports, so I don't know what will on there.

**Comment by cbaker6** [comment]
Closing as this has been answered.
